[package]
name = "tracing_json_derive"
version = "0.1.0"
edition = "2021"

[features]
default = []

[lib]
name = "tracing_json_derive"
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"